<pre class='metadata'>
Title: RDF Messages
Shortname: RDF-M
Level: 1
Status: LD
Markup Shorthands: markdown yes
URL: https://w3c-cg.github.io/rsp/spec/messages
Editor: Pieter Colpaert, https://pietercolpaert.be
Editor: Piotr Sowiński, NeverBlink https://www.neverblink.eu/, https://ostrzyciel.eu/
Repository: https://github.com/w3c-cg/rsp
Abstract: Concepts and abstract data model for RDF Messages
</pre>

# Introduction # {#introduction}

This specification defines the concepts of RDF Messages, RDF Message Streams, and RDF Message Logs, as well as the syntax for serializing RDF Message Logs in various RDF serialization formats.

The companion document [RDF Messages Tests](spec/messages-tests.bs) defines interoperability tests for RDF Message Logs and supported serialization formats.

In this document, we are discussing *message-level* streaming, where streams are sequences of discrete messages – each message may contain multiple RDF triples or quads. This is in contrast to *triple-* or *quad-level* streaming of RDF data, where streams are sequences of individual RDF triples or quads. For quad-level streaming, please refer to, for example: [[!n-quads]], [[!n-triples]], and [[!json-ld11-streaming]].

Note: Quad-level streaming is complementary to message-level streaming, and both can be used together. This is the case, for example, in the [Jelly](https://w3id.org/jelly/) serialization format, as well as some of the formats proposed in [[#rdf-message-logs-serialization]].

## RDF Messages ## {#rdf-messages}

An <dfn>RDF Message</dfn> is an [RDF Dataset](https://www.w3.org/TR/rdf12-concepts/#dfn-rdf-dataset) that is intended to be interpreted atomically as a single communicative act.
A message can be empty (contain no quads).

Note: While no formal restrictions on the size of an RDF Message are defined, RDF Messages are intended to be of limited size, in relative terms.

Note: There is no structural difference between an RDF Message and a RDF dataset. The difference is only in the intended interpretation of the data.

<figure>
<div class="example" highlight="turtle">
```turtle
PREFIX as: <https://www.w3.org/ns/activitystreams#>
PREFIX ex: <https://example.org/>

ex:like-1 a as:Like ;
  as:object ex:blogpost-1 ;
  as:actor <https://pietercolpaert.be/#me> .
```
</div>
<figcaption>Example of a social RDF Message using the [[!activitystreams-vocabulary]] vocabulary.</figcaption>
</figure>

<figure>
<div class="example" highlight="turtle">
```turtle
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX ex: <https://example.org/>

ex:obs1 a sosa:Observation ;
    sosa:observedProperty ex:TemperatureAccuracy ;
    sosa:isObservedBy ex:IBS-TH2-Plus-T-687343;
    sosa:hasResult [ 
            qudt:value 0.5 ;
            qudt:hasUnit unit:DEG_C ;
    ] .
```
</div>
<figcaption>Example of an IoT measurement RDF Message using the [[!vocab-ssn]] vocabulary.</figcaption>
</figure>

Note: This specification does not provide any mechanism for referring to an RDF Message (for example, with an IRI). You can instead refer to resources defined within the message, such as to `ex:like-1` or `ex:obs1` in the examples above.

## RDF Message Streams ## {#rdf-message-streams}

An <dfn>RDF Message Stream</dfn> is an ordered, potentially unbounded sequence of [=RDF Messages=].

Note: This concept is different from an RDF quad stream that is a stream of individual quads.

Note: This definition is intentionally abstract and simple. More details about implementing RDF Message Streams are provided in [[#producers-consumers]].

## Scope of RDF Messages ## {#scope}

By default, we assume that the [=RDF Messages=] in an [=RDF Message Stream=] are distinct and should therefore not be combined, unless an [=RDF Message Stream Profile=] overrules this default. This means that, by default, what is asserted in one message, is not asserted in other messages.

<div class="example">
For example, if each message describes the state of a domestic cat at a certain point in time, one message may report that the cat is running, while another message that the cat is sleeping. This is not a contradiction, as the messages are by default separate "worlds" that should be interpreted independently.

An [=RDF Message Stream Profile=] may indicate that all messages in a stream should be interpreted together. In this case, it could be concluded that the cat is running and sleeping at the same time, which is a contradiction.
</div>

## RDF Message Stream Producers and Consumers ## {#producers-consumers}

An <dfn>RDF Message Stream Producer</dfn> can make an [=RDF Message Stream=] available to be consumed by an <dfn>RDF Message Stream Consumer</dfn> using a stream protocol.

The underlying stream protocol is out of scope of this specification. It can be for example [[!WebSockets]], [[!LDN]], [[!EventSource]], [Linked Data Event Streams](https://w3id.org/ldes/specification), [Jelly gRPC](https://w3id.org/jelly/), [MQTT](https://mqtt.org/), or a programming language-specific stream interface that carries [=RDF Messages=], or a collection or stream of RDF Quads.

Stream protocols used for [=RDF Message Streams=] may support any streaming semantics, such as delivery guarantees, ordering, and flow control (pull-based, push-based, etc.).

Note: An RDF Message Stream can be created ad-hoc, and describes only one specific "instance" of a stream. This allows streaming protocols to have freedom in how they manage ordering, stream lifecycle, delivery guarantees, flow control, and other streaming semantics. See the examples below for more details.

<div class="example">
An HTTP server exposes a file at `https://example.org/stream`. This file contains an [=RDF Message Log=] serialization of an [=RDF Message Stream=]. A client can consume the stream by sending an HTTP GET request to that URL, and parsing the response as an [=RDF Message Stream=].

In this example, the server is the **stream producer**, and the client is the **stream consumer**. The stream protocol is HTTP. The RDF Message Stream only exists over the course of the HTTP request.
</div>

<div class="example">
An MQTT broker ([[mqtt-5]]) hosts a topic `iot/temparature` to which RDF Messages are published by an IoT thermometer. Multiple clients, at different points in time, subscribe to that topic to consume the RDF Messages being published. Because of the used Quality-of-Service settings (QoS 0), some messages maybe be lost or reordered, resulting in different clients seeing different subsets of the messages published on the topic.

In this example:

- The IoT thermometer is a **stream producer** that produces an [=RDF Message Stream=] by publishing RDF Messages to the MQTT broker, which acts as the **stream consumer**.
- For each individual client, the MQTT broker is a **stream producer** that produces an [=RDF Message Stream=] by sending RDF Messages to the client, which acts as the **stream consumer**.

For example, for 5 clients subscribing to the topic, there would be 6 different [=RDF Message Streams=]: one from the IoT thermometer to the MQTT broker, and one from the MQTT broker to each of the 5 clients. Each of these streams may have different messages in them and have a different order, due to the Quality-of-Service settings and the clients subscribing to the stream at different points in time.

Note that here we are discussing the RDF Message Stream from the perspective of the consumers. If some messages are lost between the producer and the consumer, then the two parties observe effectively two different streams.
</div>

Issue: Add a diagram illustrating RDF Messages, an RDF Message Stream, stream producers, and stream consumers.

Issue: Find out and document the similarities/differences to the [RDF-JS Stream interface](https://rdf.js.org/stream-spec/)

## RDF Message Logs ## {#rdf-message-logs}

An <dfn>RDF Message Log</dfn> is a static representation of an [=RDF Message Stream=], which can be used for archiving, sharing, and processing the messages in the stream at a later point in time. 

The log can be serialized from an [=RDF Message Stream=], and/or deserialized into an [=RDF Message Stream=].

<figure>
<div class="example" highlight="turtle">
```turtle
# a message defining the context
ex:Stream1 a ex:Dataset;
    rdfs:comment "A log of messages that appeared on a stream" .
MESSAGE # a next message is an observation in the stream
ex:Observation1
    a sosa:Observation ;
    sosa:resultTime "2026-01-01T00:00:00Z"^^xsd:dateTime ;
    sosa:hasSimpleResult "..." .
MESSAGE # an empty message
MESSAGE # another observation
ex:Observation2
    a sosa:Observation ;
    sosa:resultTime "2026-01-01T00:10:00Z"^^xsd:dateTime ;
    sosa:hasSimpleResult "..." .	
```
</div>
<figcaption>Example of an [=RDF Message Log=] publishing the [=RDF Messages=] that appeared in a stream so far.</figcaption>
</figure>

Issue: Can we provide an example of an RDF Message Log that does not use any of the formats that we define in the next section, to illustrate the concept of an RDF Message Log without relying on the syntax of a specific format?

Note: A producer may want to indicate that a certain property is used to indicate the timestamp of when the message was created. This can be done, for example, using `ldes:timestampPath` from [Linked Data Event Streams](https://w3id.org/ldes/specification). Alternatively, when vocabularies such as ActivityStreams, SSN/SOSA, or PROV-O are used, one can just assume the respective properties `as:published`, `sosa:resultTime`, or `prov:generatedAtTime` are going to be used for this purpose.

Blank node identifiers in RDF Message Streams and RDF Message Logs are scoped to the message they occur in. This allows for processing very long streams without having to worry about blank node identifier collisions or memory exhaustion. In case messages need to be linked together, it is recommended to use IRIs or skolemization.

## Version labels ## {#version-labels}

RDF 1.2 [[!rdf12-concepts]] defines version labels, which identify the syntax and semantics conformance for the RDF data. RDF 1.2 defines three version labels: "1.1", "1.2", and "1.2-basic". RDF Messages extends this scheme with three new version labels, as shown in the table below.

<figure class=table>
<figcaption class=table>Version labels for RDF Messages.</figcaption>
<table class=simple>
  <thead>
    <tr>
      <th>Version label</th>
      <th>Base syntax</th>
      <th>Triple terms</th>
      <th>RDF Messages</th>
      <th>Semantics</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>"1.2-messages"</td>
      <td>RDF 1.2</td>
      <td><strong>yes</strong></td>
      <td><strong>yes</strong></td>
      <td>[[!rdf12-semantics]]</td>
    </tr>
    <tr>
      <td>"1.2"</td>
      <td>RDF 1.2</td>
      <td><strong>yes</strong></td>
      <td>no</td>
      <td>[[!rdf12-semantics]]</td>
    </tr>
    <tr>
      <td>"1.2-basic-messages"</td>
      <td>RDF 1.2</td>
      <td>no</td>
      <td><strong>yes</strong></td>
      <td>[[!rdf12-semantics]]</td>
    </tr>
    <tr>
      <td>"1.2-basic"</td>
      <td>RDF 1.2</td>
      <td>no</td>
      <td>no</td>
      <td>[[!rdf12-semantics]]</td>
    </tr>
    <tr>
      <td>"1.1-messages"</td>
      <td>RDF 1.1</td>
      <td>no</td>
      <td><strong>yes</strong></td>
      <!-- TODO: fix bibliography -->
      <td>rdf11-semantics</td>
    </tr>
    <tr>
      <td>"1.1"</td>
      <td>RDF 1.1</td>
      <td>no</td>
      <td>no</td>
      <!-- TODO: fix bibliography -->
      <td>rdf11-semantics</td>
    </tr>
  </tbody>
</table>
</figure>

Data conforming to version labels without the "-messages" suffix is valid as data with version with this suffix added. For example, data conforming to version "1.2" is also valid as data with version "1.2-messages".

Additionally, same conformance rules as defined for the "1.1", "1.2", and "1.2-basic" version labels apply to the "1.1-messages", "1.2-messages", and "1.2-basic-messages" version labels, respectively. Namely, data conforming to version "1.1-messages" is valid as data with version "1.2-basic-messages", and data conforming to version "1.2-basic-messages" is valid as data with version "1.2-messages".

Version announcement should be done using the mechanisms defined in [[!rdf12-concepts]]: the `version` parameter in the `Content-Type` and `Accept` headers for HTTP, and the serialization format-specific in-line version announcements (e.g., `VERSION` in Turtle).

<div class="example">
Requesting an N-Triples RDF Message Log with RDF 1.2 semantics and support for triple terms:

```http
GET /message-log.nt HTTP/1.1
Host: example.org
Accept: application/n-triples; version=1.2-messages
```
</div>

<div class="example">
Requesting a TriG RDF Message Log with RDF 1.1 semantics:

```http
GET /message-log.trig HTTP/1.1
Host: example.org
Accept: application/trig; version=1.1-messages
```
</div>



# Serializing and parsing RDF Message Logs # {#rdf-message-logs-serialization}

In this specification we propose that all RDF serializations MUST implement a way to group quads into [=RDF Messages=].
This way, a [=RDF Message Stream Consumer=] can write the stream into an [=RDF Message Log=] that can be read again by a [=RDF Message Stream Producer=] into an [=RDF Message Stream=].

Note: While we do define content types for the RDF Message Log serialization formats, this does not imply that the serialization needs to be used over HTTP only. The use of alternative transport mechanisms is equally valid and encouraged.

## N-Triples, N-Quads, Turtle, and TriG ## {#turtle}

We propose to extend the existing N-Triples, N-Quads, Turtle, and TriG formats to support RDF Messages. These extended formats are NOT backwards-compatible with existing parsers, as they require support for the new [[#message-delimiters]] syntax.

### Version announcement ### {#version-announcement}

Concrete RDF syntaxes (e.g., [[!rdf12-turtle]]) are being revised in RDF 1.2 to support in-line version announcements. This allows for communicating to the parser which features of the syntax are used in the file.

We extend this mechanism by adding three new version labels for RDF syntaxes that support RDF Messages (see [[#version-labels]]). If a parser encounters a version label with the "-messages" suffix, it should expect the file to `MESSAGE` directives. Therefore, if the parser does not support RDF Messages, it should reject the file as invalid.

In N-Triples ([[!rdf12-n-triples]]) and N-Quads ([[!rdf12-n-quads]]), the version announcement has one legal form (`VERSION`):

<div class="example">
```turtle
VERSION "1.2-messages"
<http://example.org/spiderman> <http://example.org/enemyOf> <http://example.org/green-goblin> .
```
</div>

In Turtle ([[!rdf12-turtle]]) and TriG ([[!rdf12-trig]]), the version announcement can be done in the same manner:

<div class="example">
```turtle
VERSION "1.2-basic-messages"
PREFIX ex: <http://example.org/>
ex:spiderman ex:enemyOf ex:green-goblin .
```
</div>

Or, alternatively, with the old-style `@version` directive:

<div class="example">
```turtle
@version "1.1-messages" .
@prefix ex: <http://example.org/> .
ex:spiderman ex:enemyOf ex:green-goblin .
```
</div>



### Message delimiters ### {#message-delimiters}

When the version label of the document being parsed has the "-messages" suffix, the parser MUST:

 1. Consider every triple or quad in the document as part of an [=RDF Message=].
 2. Triples or quads are added to the current message as long as no delimiter or EOF has been encountered.
 3. When a delimiter is encountered, the current [=RDF Message=] is finalized. The next message is opened only if a triple, quad, or another delimiter is encountered after the current delimiter.
 4. If a delimiter is encountered before any triple or quad in the document, that means that the first message is empty.
 5. When the end of the file is reached, the current [=RDF Message=] is finalized.

Note: A dedicated message delimiter syntax is required because comments are ignored by RDF parsers and therefore cannot reliably delimit messages. Also, each message may have its own implicit context or profile, and blank node scoping is defined per message. A new syntax makes these message-level semantics explicit and avoids accidental cross-message assertions or blank node collisions.

For N-Triples and N-Quads, the `directive` grammar production is extended as follows:

```ebnf
directive        ::= versionDirective | messageDirective
messageDirective ::= 'MESSAGE'
```

For example, this is an N-Triples file with two messages:

<div class="example">
```turtle
VERSION "1.2-messages"
<http://example.org/message_1> <http://example.org/hasValue> "Hello, world!" .
<http://example.org/message_1> <http://example.org/hasNumber> "1" .
MESSAGE
<http://example.org/message_2> <http://example.org/hasValue> "Goodbye, world!" .
```
</div>

This is a file with one empty message followed by one message with two triples:

<div class="example">
```turtle
VERSION "1.2-messages"
MESSAGE
<http://example.org/message_1> <http://example.org/hasValue> "Hello, world!" .
<http://example.org/message_1> <http://example.org/hasNumber> "2" .
```
</div>

And this is a file with only one message with one triple:

<div class="example">
```turtle
VERSION "1.2-messages"
<http://example.org/message_1> <http://example.org/hasValue> "Hello, world!" .
MESSAGE
```
</div>

For Turtle and TriG, the `directive` grammar production is extended as follows:

```ebnf
directive     ::= prefixID | base | version | message
                  | sparqlPrefix | sparqlBase | sparqlVersion | sparqlMessage
message       ::= '@message' '.'
sparqlMessage ::= 'MESSAGE'
```

For example, this is a TriG file with two messages:

<div class="example">
```turtle
VERSION "1.2-messages"
PREFIX ex: <http://example.org/>
ex:message_1 {
  ex:person ex:says "Hello, world!" ;
}
ex:message_1 ex:hasNumber 1 .
MESSAGE
ex:message_2 {
  ex:person ex:says "Goodbye, world!" ;
}
ex:message_2 ex:hasNumber 2 .
MESSAGE
```
</div>

And this is a Turtle file with two messages in the old-style syntax:

<div class="example">
```turtle
@version "1.2-messages" .
@prefix ex: <http://example.org/> .
ex:person ex:says "Hello, world!" .
@message .
ex:person ex:says "Goodbye, world!" .
```
</div>

Note: Because blank node identifiers are scoped to the message they occur in, the same blank node identifier can be used in different messages without causing collisions. Typically parsers that insert triples/quads into an RDF store remap blank node identifiers from the parsed file to internal identifiers. To implement RDF Messages, parsers should reset their blank node identifier mapping when a message delimiter is encountered, so that the same blank node identifier can be reused in the next message in the log without causing collisions.

### Repeated PREFIX and BASE directives ### {#prefixes-and-base-iris}

Repated `PREFIX` and `BASE` directives are allowed in Turtle and TriG RDF Message Logs – see [Example 12 in RDF 1.2 Turtle](https://www.w3.org/TR/rdf12-turtle/#ex-turtle-abbreviations). If, for example, `PREFIX ex:` is defined in the document, and then later `PREFIX ex:` is defined again with a different IRI, the second definition will override the first one for the rest of the document.

Similarly, repeated `PREFIX` and `BASE` directives are allowed in RDF Message Logs, making it possible to easily concatenate Turtle / TriG files into RDF Message Logs.

In this example, the first message uses the `ex:` prefix to refer to `http://example.org/`, while the second message uses the same prefix to refer to `http://different-iri.org/`:

<div class="example">
```turtle
VERSION "1.2-messages"
PREFIX ex: <http://example.org/>
ex:person ex:says "Hello, world!" .
MESSAGE
PREFIX ex: <http://different-iri.org/>
ex:person ex:says "Goodbye, world!" .
```
</div>



## JSON-LD ## {#json-ld}

Issue: This discussion is preliminary, yet on-going, in the JSON-LD group itself with a proposal called [newline delimited JSON-LD](https://github.com/json-ld/ndjson-ld/issues/1). We propose that that specification becomes the preferred way of adding messages support in JSON-LD. It is [already implemented in some libraries](https://github.com/eclipse-rdf4j/rdf4j/issues/2840) and it is already being used in some projects.

We propose to use the [unofficial NDJSON-LD format](https://github.com/json-ld/ndjson-ld) as the serialization format for [=RDF Message Logs=] in JSON-LD. In [NDJSON](https://github.com/ndjson/ndjson-spec), multiple JSON objects are concatenated together, with each object being separated by a newline character (`\n`). NDJSON-LD simply applies this format to JSON-LD documents, where each each line corresponds to an [=RDF Message=].

Issue: What should be the content type for this format? RDF4J currently uses `application/x-ld+ndjson` – [see the pull request](https://github.com/eclipse-rdf4j/rdf4j/pull/2845).

<figure>
<div class="example" highlight="json">
```json
{"@context": "https://schema.org/", "@type": "Product", "name": "Hairdryer DRY 2000", "color": "red"}
{"@context": "https://schema.org/", "@type": "Product", "name": "27-inch 4K Monitor 2700P", "color": "black"}
```
</div>
<figcaption>Example of an [=RDF Message Log=] in the NDJSON-LD serialization format.</figcaption>
</figure>

## YAML-LD ## {#yaml-ld}

Issue: Tracked as <w3c-cg/rsp#4>. The format proposed here is incompatible with the [YAML-LD Final Community Group Report](https://www.w3.org/community/reports/json-ld/CG-FINAL-yaml-ld-20231206/), which proposes to instead transform YAML streams into a top-level array in a JSON-LD document. The discussion on this topic is still on-going and must be resolved in collaboration with the newly-rechartered JSON-LD WG.

The [[!YAML]] format includes built-in support for *YAML streams*, where multiple YAML documents are concatenated together, with each document being separated typically by a line containing three dashes (`---`). We propose to use that mechanism to serialize [=RDF Message Logs=], where each YAML document corresponds to an [=RDF Message=].

This is made discoverable with a new content-type: `Content-Type: application/rdfm+yaml`

Issue: Is this the correct content type?

<figure>
<div class="example" highlight="yaml">
```yaml
"@context": https://schema.org/
"@type": Product
name: Hairdryer DRY 2000
color: red
---
"@context": https://schema.org/
"@type": Product
name: 27-inch 4K Monitor 2700P
color: black
```
</div>
<figcaption>Example of an [=RDF Message Log=] in the YAML-LD serialization format.</figcaption>
</figure>

## RDF/XML ## {#rdf-xml}

Each message is a new XML document on a new line. The documents are separated with the `\n` character.

This is made discoverable with a new content-type: `Content-Type: application/rdfm+xml`

<figure>
<div class="example" highlight="xml">
<xmp>
<?xml version="1.0" encoding="utf-8"?><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:schema="http://schema.org/"><rdf:Description rdf:nodeID="b3"><rdf:type rdf:resource="http://schema.org/Product"/><schema:name>Hairdryer DRY 2000</schema:name><schema:color>red</schema:color></rdf:Description></rdf:RDF>
<?xml version="1.0" encoding="utf-8"?><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:schema="http://schema.org/"><rdf:Description rdf:nodeID="b3"><rdf:type rdf:resource="http://schema.org/Product"/><schema:name>27-inch 4K Monitor 2700P</schema:name><schema:color>black</schema:color></rdf:Description></rdf:RDF>
</xmp>
</div>
<figcaption>Example of an [=RDF Message Log=] in the RDF/XML serialization format.</figcaption>
</figure>

Issue: Is there a different industry-standard way to serialize multiple RDF/XML documents into a single file?

## Other formats ## {#other-formats}

Efficient interchange of [=RDF Message Logs=] may also be done using binary RDF serializations, such as [Jelly](https://w3id.org/jelly/), which already has built-in support for grouping quads into messages. We propose that Jelly and similar formats use the definitions from this specification to define the semantics of RDF Messages.

# RDF Message Stream Profiles # {#rdf-message-stream-profiles}

Issue: Write down the section on profiles. Tracked as <w3c-cg/rsp#1>.

An <dfn>RDF Message Stream Profile</dfn> is a ... (TODO)

# Examples and use cases # {#examples}

## An archive of an RDF Stream ## {#stream-archive}

When you write out an [=RDF Message Log=] into a file, all [=RDF Messages=] are preserved when deserializing it again.
They are streamed out in the same order as they were written into the file.

Without the semantics of an [=RDF Message=], and without the syntax for it, trying to reconstruct the intended message becomes slow and cannot be solved without using sub-optimal heuristics.
The performance loss is due to the fact that there could always be another quad at the end of the file that still needs to be considered for the message, as you cannot rely on the quads being grouped together.
A heuristic is needed as you can only guess that e.g. subject-based star patterns, or maybe a [[!CBD]], or maybe a named graph is going to be used.
This is what is being used by [the Linked Data Event Streams “member extraction” step](https://semiceu.github.io/LinkedDataEventStreams/#members).

## SPARQL CONSTRUCT results ## {#sparql-construct-messages}

<figure>
<div class="example" highlight="sparql">
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
CONSTRUCT {
  ?company a dbo:Company ;
       dbo:location ?location .
  
  ?location rdf:type dbo:Country ;
            rdfs:label ?lname ;
            dbp:populationCensus ?pop .
} WHERE {
    ?company dbo:location | dbo:locationCountry ?location .
    
    ?location rdf:type dbo:Country ;
              rdfs:label ?lname ;
              dbp:populationCensus | dbo:populationTotal ?pop .
    
    FILTER (LANG(?lname) = "en")
} ORDER BY ?location LIMIT 10000
```
</div>
<figcaption>If the query engine would support RDF Message Logs to indicate that groups of triples are part of a certain result, it would speed up clients that want to use the message as a meaningful concept.</figcaption>
</figure>

<!-- TODO: fix the example, the query times out currently -->

The example (Test it using the [DBpedia SPARQL endpoint](https://dbpedia.org/sparql)) generates 10000 companies in countries and lists the population number of the country.
Now imagine that a consumer wants to process the results of this SPARQL query, where each construct result is an [=RDF Message=].
While the server could have grouped the quads for the consumer, the consumer will have to re-construct the BGP in the CONSTRUCT clause again on the client before it can proceed.
The obvious solution here is to use an [=RDF Message Stream=].

## RiverBench dataset distributions ## {#riverbench-dataset-distributions}

Benchmark datasets in [RiverBench](https://w3id.org/riverbench/) are streams of RDF datasets, where each RDF dataset can be processed individually as an RDF Message. They represent real-world use cases of streaming RDF data.
For example, the [officegraph dataset](https://w3id.org/riverbench/datasets/officegraph/dev) consists of almost 15 million RDF graphs with IoT measurements (see example below).

<figure>
<div class="example" highlight="turtle">
```turtle
PREFIX ic:    <https://interconnectproject.eu/example/>
PREFIX om:    <http://www.wurvoc.org/vocabularies/om-1.8/>
PREFIX saref: <https://saref.etsi.org/core/>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>

ic:property_R5_56__co2_
        a       ic:CO2Level .

ic:measurement_R5_56__co2__0
        a                        saref:Measurement;
        saref:hasTimestamp       "2022-02-28T23:59:00"^^xsd:dateTime;
        saref:hasValue           "504"^^xsd:float;
        saref:isMeasuredIn       om:partsPerMillion;
        saref:relatesToProperty  ic:property_R5_56__co2_ .
```
</div>
<figcaption>Example of an RDF Message in the officegraph dataset.</figcaption>
</figure>

To distribute this stream, a TAR archive is used, where each file in the archive is an RDF Message in the stream.
This could be greatly improved by using an [=RDF Message Log=] serialization instead, as this would allow to save the entire stream into a single file, while still being able to reconstruct the individual messages again.

As an alternative, [Jelly-RDF](https://w3id.org/jelly) distributions are also available, where the entire stream is serialized as a single `.jelly` file. In the file, one [Jelly frame](https://w3id.org/jelly/dev/user-guide/#stream-frames) corresponds to one RDF dataset. Under this specification, this would be a valid [=RDF Message Log=] serialization.

## Nanopublications ## {#nanopublications}

A [Nanopublication](https://nanopub.net/) is a small RDF dataset that contains an assertion, its provenance, and publication information. Nanopublications are stored and exchanged by a network of services (registries and query endpoints). Exchanging each Nanopublication individually leads to significant overhead, due to repeated HTTP requests necessitated by the lack of a format for grouping multiple Nanopublications together. This issue was resolved by using [Jelly](https://w3id.org/jelly/) to serialize multiple Nanopublications into a single byte stream, where each Nanopublication corresponds to a [Jelly frame](https://w3id.org/jelly/dev/user-guide/#stream-frames).

Using an [=RDF Message Log=] serialization to group multiple Nanopublications into a single file would also solve this problem, while still allowing each Nanopublication to be processed individually as an [=RDF Message=].


<pre class=biblio>
{
  "mqtt-5": {
    "authors": [
      "Andrew Banks",
      "Ed Briggs",
      "Ken Borgendale",
      "Rahul Gupta"
    ],
    "href": "https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html",
    "title": "MQTT Version 5.0",
    "status": "OASIS Standard",
    "publisher": "OASIS",
    "deliveredBy": [
      "https://www.oasis-open.org/committees/mqtt/"
    ]
  }
}
</pre>

<style>
table { border-collapse: collapse }
table.simple td, table th { border: 1px solid #444; padding: 0.2em 0.5em; }
</style>